[package]
# TODO fix `authors` if you didn't use `cargo-generate`
authors = ["yud0uhu"]
name = "testsuite"
publish = false
edition = "2021"
version = "0.1.0"

[lib]
harness = false

[[test]]
name = "test"
harness = false

[dependencies]
arm-rs-rtos = { path = ".." }